### GENERAL SETTINGS ###

# Site settings
title: science to action

analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl:   #'' should be ok, if doesn't work try a /
url: "https://global-change.github.io/science_to_action/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#014f7e" #"#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#232b34"  #"#384452" #"#33004D"
  link: "#016fb1" #"#428bca"
  link_hover: "#016fb1" #"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


